services:
  goseek:
    image: goodieshq/goseek:latest
    container_name: goseek
    restart: unless-stopped
    environment:
      GOSEEK_CONFIG_PATH: /app/config.yml
    volumes:
      - ./config.yml:/app/config.yml
      - ./root:/app/root:ro
    ports:
      - 3000:80
  goseek_sftp:
    image: atmoz/sftp:latest
    container_name: goseek_sftp
    restart: unless-stopped
    ports:
      - "2222:22"
    volumes:
      - ./root:/home/sftpuser
    command: sftpusername:sftppassword:1000